apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cat-prod

replicas:
- name: cat-server
  count: 3
  
images:
- name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/wpernath/grumpycat-melonjs
  newTag: v0.6.6
- name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/wpernath/quarkus-grumpycat
  newTag: v0.6.6

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-prod.apps.cluster-fkqfj.fkqfj.sandbox1665.opentlc.com/
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
